<a href="https://colab.research.google.com/github/Haykalilys/tugas_DesainAnalisisAlgoritma/blob/master/Latihan_Pertemuan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
aList = ["John", 33, "Toronto", True]
print(aList)


['John', 33, 'Toronto', True]


In [4]:
# warna
bin_colors=['red','green','blue','yellow']
for aColor in bin_colors:
  print("Square " + aColor )

Square red
Square green
Square blue
Square yellow


In [1]:
# mahasiswa
bin_colors=['haykal','junedi','malik','saputro']
for aColor in bin_colors:
  print("UPJ " + aColor )

UPJ haykal
UPJ junedi
UPJ malik
UPJ saputro


In [2]:

bin_color=['Red', 'Green', 'Blue',  'Yellow' ]
bin_color[0:3]



['Red', 'Green', 'Blue']

In [3]:

bin_colors=('Red','Green','Blue','Yellow')
bin_colors[1:3]


('Green', 'Blue')

In [6]:
hariAwal = ("senin","selasa","rabu")
hariAkhir = ("kamis","jumat","sabtu")
hari = (hariAwal, hariAkhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


In [7]:
bin_colors ={ "manual_color": "Yellow", "approved_color": "Green", "refused_color": "Red" }
print(bin_colors)

bin_colors['approved_color']="Purple"
print(bin_colors)
{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}
{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}

In [8]:
# jika mencoba menambahkan elemen redundan lainny, itu akan mengabaikannya
green = {'grass', 'leaves', 'leaves'}
print(green)

{'leaves', 'grass'}


In [9]:
nama = "Haykal Kamal Ilyasa"
NIM = 2022071072
prodi = "Informatika"
universitas = "UPJ"

print(nama, NIM)

Haykal Kamal Ilyasa 2022071072


In [10]:
set_04 = {1,2,3,4,5,6,7,8}
set_04.discard(4) #hapus nilai 4
set_04.add(10) #menambahkan nilai 10
print(set_04)

{1, 2, 3, 5, 6, 7, 8, 10}


In [11]:
# union adalah saat kita menggabungkan semua anggota set.
set_A = {1,2,3,4}
set_B = {3,4,5,6}
print(set_A | set_B)
print(set_A.union(set_B))


# intersection adalah irisan, dimana kita mencari nilai irisan dari sebuah set.
set_A = {1,2,3,4}
set_B = {3,4,5,6}
print(set_A & set_B)
print(set_A.intersection(set_B))


# difference adalah operasi saat kita mencari perbedaan anggota dari dua buah set atau lbih
set_A = {1,2,3,4}
set_B = {3,4,5,6}
# A-B
print(set_A - set_B)
print(set_A.difference(set_B))
# B-A
print(set_B - set_A)
print(set_B.difference(set_A))

# symmetric difference adalah semua anggota pada set A dan B dikurangi dengan anggota yang berada pada dua set tersebut.
set_A = {1,2,3,4}
set_B = {3,4,5,6}

print(set_A ^ set_B)
print(set_A.symmetric_difference(set_B))





{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}
{3, 4}
{3, 4}
{1, 2}
{1, 2}
{5, 6}
{5, 6}
{1, 2, 5, 6}
{1, 2, 5, 6}


In [12]:
import datetime

x = datetime.datetime.now()
Mahasiswa = ["Haykal", 2022071072, "Informatika", "DAA", x, "Universitas Pembangunan Jaya"]
print(Mahasiswa)

print(x)


['Haykal', 2022071072, 'Informatika', 'DAA', datetime.datetime(2023, 9, 17, 5, 59, 24, 710921), 'Universitas Pembangunan Jaya']
2023-09-17 05:59:24.710921


In [13]:
# df.columns = ['id', 'name', 'age', 'decision’]
import pandas as pd
df = pd.DataFrame([ ['1', 'Fares', 32, True], ['2', 'Elena', 23, False], ['3', 'Steven', 40, True]])
print(df)

   0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True


In [14]:
data = {'satu': [1,1,1,1,1], 'dua' : [2,2,2,2,2], 'tiga': [3,3,3,3,3]}
df = pd.DataFrame(data, index=['a','b','c','d','e'])
df.head()

satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3

In [5]:
import numpy as np
matriksC = np.array([[1,2,3], [4,5,6]])
print("Matriks C : ")
print(matriksC)
transpose_matriks = np.transpose(matriksC)
print("Tranpose Matriks C : ")
print(transpose_matriks)

Matriks C : 
[[1 2 3]
 [4 5 6]]
Tranpose Matriks C : 
[[1 4]
 [2 5]
 [3 6]]


In [6]:
# Latihan
import numpy as np
matriksC = np.array([[100,200,300], [700,600,500], [900,100,800]])

transpose_matriks = np.transpose(matriksC)
print("Tranpose Matriks C : ")
print(transpose_matriks)

Tranpose Matriks C : 
[[100 700 900]
 [200 600 100]
 [300 500 800]]


In [16]:
# menggunakan list python
myVector = [22,33,44,55]
print(myVector)
[22, 33, 44, 55]
print(type(myVector))


[22, 33, 44, 55]
<class 'list'>


In [18]:
# menggunakan array numpy
myVector = np.array([22,33,44,55])
print(myVector)
[22, 33, 44, 55]
print(type(myVector))


[22 33 44 55]
<class 'numpy.ndarray'>
